export const themes = {
    sunset: {
        bgImage: "/Sunset/BackgroundSunset.gif",
        audioSrc: "/Sunset/AudioSunset.mp3",
        audioTitle: "Deja Vu",
        audioArtist: "Purrple Cat",
        themeColor: "#ef9068",
        audioTheme: "Sunset Mellow",
        objectPositionSm: "50% 50%",
        objectPositionLg: "bottom left",
    },
    gardening: {
        bgImage: "/Gardening/BackgroundGardening.gif",
        audioSrc: "/Gardening/AudioGardening.mp3",
        audioTitle: "Princess Mononoke",
        audioArtist: "Lofi Lia",
        themeColor: "#7bffd2",
        audioTheme: "Gardening Vibes",
        objectPositionSm: "50% 50%",
        objectPositionLg: "center",
    },
    nightride: {
        bgImage: "/NightRide/BackgroundNightRide.gif",
        audioSrc: "/NightRide/AudioNightRide.mp3",
        audioTitle: "Neon Drive",
        audioArtist: "Tokyo Lofi",
        themeColor: "#607d8b",
        audioTheme: "Night Ride",
        objectPositionSm: "50% 50%",
        objectPositionLg: "center",
    },
    amandat: {
        bgImage: "/AmandaT/BackgroundAmandaT.gif",
        audioSrc: "/AmandaT/AudioAmandaT.mp3",
        audioTitle: "Tokyo Atmosphere",
        audioArtist: "Lofi Tokyo",
        themeColor: "#f1c276",
        audioTheme: "Amanda T",
        objectPositionSm: "center bottom",
        objectPositionLg: "center bottom",
        hidden: true, // Hides from menu
    },
    amanda: {
        bgVideo: "/Amanda/BackgroundAmanda.mp4",
        audioSrc: "/Amanda/AudioAmanda.mp3",
        audioTitle: "Always With Me (Lo-fi)",
        audioArtist: "Shoyo",
        themeColor: "#c097cc",
        audioTheme: "Amanda",
        objectPositionSm: "15% 85%",
        objectPositionLg: "left",
        hidden: true, // Hides from menu
    },
    gina: {
        bgVideo: "/Gina/BackgroundGina.mp4",
        audioSrc: "/Gina/AudioGina.mp3",
        audioTitle: "In A Manner Of Speaking",
        audioArtist: "Nouvelle Vague",
        themeColor: "#721A07",
        audioTheme: "Gina",
        objectPositionSm: "15% 85%",
        objectPositionLg: "left",
        hidden: true, // Hides from menu
    },
    cafe: {
        bgImage: "/Cafe/BackgroundCafe.gif",
        audioSrc: "/Cafe/AudioCafe.mp3",
        audioTitle: "this is for you",
        audioArtist: "LuKremBo",
        themeColor: "#f1c276",
        audioTheme: "Cafe Hustle",
        objectPositionSm: "50% 50%",
        objectPositionLg: "center",
    },
    study: {
        bgImage: "/Study/BackgroundStudy.gif",
        audioSrc: "/Study/AudioStudy.mp3",
        audioTitle: "Yamiyo Lo-fi",
        audioArtist: "Kijugo",
        themeColor: "#d15f50",
        audioTheme: "Study Mode",
        objectPositionSm: "left 20%",
        objectPositionLg: "center",
    },
    rain: {
        bgImage: "/Rain/BackgroundRain.gif",
        audioSrc: "/Rain/AudioRain.mp3",
        audioTitle: "Of Frogs & Lilypads",
        audioArtist: "Seycara",
        themeColor: "#b3dedc",
        audioTheme: "Rainy Reverie",
        objectPositionSm: "50% 50%",
        objectPositionLg: "center",
    },
    work: {
        bgImage: "/Work/BackgroundWork.gif",
        audioSrc: "/Work/AudioWork.mp3",
        audioTitle: "Show Me How",
        audioArtist: "Men I Trust",
        themeColor: "#e5d6ae",
        audioTheme: "Work Flow",
        objectPositionSm: "20% 0",
        objectPositionLg: "left",
    },
    space: {
        bgImage: "/Space/BackgroundSpace.gif",
        audioSrc: "/Space/AudioSpace.mp3",
        audioTitle: "Reflection",
        audioArtist: "Purrple Cat",
        themeColor: "#f40ee7",
        audioTheme: "Alone in Space",
        objectPositionSm: "50% 50%",
        objectPositionLg: "center",
    },
    waiting: {
        bgVideo: "/Waiting/BackgroundWaiting.mp4",
        audioSrc: "/Waiting/AudioWaiting.mp3",
        audioTitle: "Moon",
        audioArtist: "Nem",
        themeColor: "#3e496a",
        audioTheme: "Waiting for you",
        objectPositionSm: "50% 50%",
        objectPositionLg: "center",
    },
    debit: {
        bgImage: "/Debit/BackgroundDebit.gif",
        audioSrc: "/Debit/AudioDebit.mp3",
        audioTitle: "跳楼机",
        audioArtist: "LBI利比",
        themeColor: "#a0d8ee",
        audioTheme: "Debit",
        objectPositionSm: "30% 50%",
        objectPositionLg: "left",
        hidden: true,

    },
};